create extension if not exists "uuid-ossp";

create table if not exists "country"
(
    id       UUID unique  not null default uuid_generate_v1() primary key,
    name varchar(255) not null,
    code varchar(50)  not null,
    last_modify_date date not null
);

insert into country.country (name, code, last_modify_date)
values ('Fiji', 'FJ', CURRENT_DATE),
       ('Tanzania', 'TZ', CURRENT_DATE),
       ('Western Sahara', 'EH', CURRENT_DATE),
       ('Canada', 'CA', CURRENT_DATE),
       ('United States', 'US', CURRENT_DATE),
       ('Kazakhstan', 'KZ', CURRENT_DATE),
       ('Uzbekistan', 'UZ', CURRENT_DATE),
       ('Papua New Guinea', 'PG', CURRENT_DATE),
       ('Indonesia', 'ID', CURRENT_DATE),
       ('Argentina', 'AR', CURRENT_DATE),
       ('Chile', 'CL', CURRENT_DATE),
       ('Democratic Republic of the Congo', 'CD', CURRENT_DATE),
       ('Somalia', 'SO', CURRENT_DATE),
       ('Kenya', 'KE', CURRENT_DATE),
       ('Sudan', 'SD', CURRENT_DATE),
       ('Chad', 'TD', CURRENT_DATE),
       ('Haiti', 'HT', CURRENT_DATE),
       ('Dominican Republic', 'DO', CURRENT_DATE),
       ('Russia', 'RU', CURRENT_DATE),
       ('Bahamas', 'BS', CURRENT_DATE),
       ('Falkland Islands', 'FK', CURRENT_DATE),
       ('Norway', 'NO', CURRENT_DATE),
       ('Greenland', 'GL', CURRENT_DATE),
       ('Timor-Leste', 'TL', CURRENT_DATE),
       ('South Africa', 'ZA', CURRENT_DATE),
       ('Lesotho', 'LS', CURRENT_DATE),
       ('Mexico', 'MX', CURRENT_DATE),
       ('Uruguay', 'UY', CURRENT_DATE),
       ('Brazil', 'BR', CURRENT_DATE),
       ('Bolivia', 'BO', CURRENT_DATE),
       ('Peru', 'PE', CURRENT_DATE),
       ('Colombia', 'CO', CURRENT_DATE),
       ('Panama', 'PA', CURRENT_DATE),
       ('Costa Rica', 'CR', CURRENT_DATE),
       ('Nicaragua', 'NI', CURRENT_DATE),
       ('Honduras', 'HN', CURRENT_DATE),
       ('El Salvador', 'SV', CURRENT_DATE),
       ('Guatemala', 'GT', CURRENT_DATE),
       ('Belize', 'BZ', CURRENT_DATE),
       ('Venezuela', 'VE', CURRENT_DATE),
       ('Guyana', 'GY', CURRENT_DATE),
       ('Suriname', 'SR', CURRENT_DATE),
       ('France', 'FR', CURRENT_DATE),
       ('Ecuador', 'EC', CURRENT_DATE),
       ('Puerto Rico', 'PR', CURRENT_DATE),
       ('Jamaica', 'JM', CURRENT_DATE),
       ('Cuba', 'CU', CURRENT_DATE),
       ('Zimbabwe', 'ZW', CURRENT_DATE),
       ('Botswana', 'BW', CURRENT_DATE),
       ('Namibia', 'NA', CURRENT_DATE),
       ('Senegal', 'SN', CURRENT_DATE),
       ('Mali', 'ML', CURRENT_DATE),
       ('Mauritania', 'MR', CURRENT_DATE),
       ('Benin', 'BJ', CURRENT_DATE),
       ('Niger', 'NE', CURRENT_DATE),
       ('Nigeria', 'NG', CURRENT_DATE),
       ('Cameroon', 'CM', CURRENT_DATE),
       ('Togo', 'TG', CURRENT_DATE),
       ('Ghana', 'GH', CURRENT_DATE),
       ('Guinea', 'GN', CURRENT_DATE),
       ('Guinea-Bissau', 'GW', CURRENT_DATE),
       ('Liberia', 'LR', CURRENT_DATE),
       ('Sierra Leone', 'SL', CURRENT_DATE),
       ('Burkina Faso', 'BF', CURRENT_DATE),
       ('Central African Republic', 'CF', CURRENT_DATE),
       ('Republic of the Congo', 'CG', CURRENT_DATE),
       ('Gabon', 'GA', CURRENT_DATE),
       ('Equatorial Guinea', 'GQ', CURRENT_DATE),
       ('Zambia', 'ZM', CURRENT_DATE),
       ('Malawi', 'MW', CURRENT_DATE),
       ('Mozambique', 'MZ', CURRENT_DATE),
       ('Eswatini', 'SZ', CURRENT_DATE),
       ('Angola', 'AO', CURRENT_DATE),
       ('Burundi', 'BI', CURRENT_DATE),
       ('Israel', 'IL', CURRENT_DATE),
       ('Lebanon', 'LB', CURRENT_DATE),
       ('Madagascar', 'MG', CURRENT_DATE),
       ('Palestine', 'PS', CURRENT_DATE),
       ('The Gambia', 'GM', CURRENT_DATE),
       ('Tunisia', 'TN', CURRENT_DATE),
       ('Algeria', 'DZ', CURRENT_DATE),
       ('Jordan', 'JO', CURRENT_DATE),
       ('United Arab Emirates', 'AE', CURRENT_DATE),
       ('Qatar', 'QA', CURRENT_DATE),
       ('Kuwait', 'KW', CURRENT_DATE),
       ('Iraq', 'IQ', CURRENT_DATE),
       ('Oman', 'OM', CURRENT_DATE),
       ('Vanuatu', 'VU', CURRENT_DATE),
       ('Cambodia', 'KH', CURRENT_DATE),
       ('Thailand', 'TH', CURRENT_DATE),
       ('Lao PDR', 'LA', CURRENT_DATE),
       ('Myanmar', 'MM', CURRENT_DATE),
       ('Vietnam', 'VN', CURRENT_DATE),
       ('Dem. Rep. Korea', 'KP', CURRENT_DATE),
       ('Republic of Korea', 'KR', CURRENT_DATE),
       ('Mongolia', 'MN', CURRENT_DATE),
       ('India', 'IN', CURRENT_DATE),
       ('Bangladesh', 'BD', CURRENT_DATE),
       ('Bhutan', 'BT', CURRENT_DATE),
       ('Nepal', 'NP', CURRENT_DATE),
       ('Pakistan', 'PK', CURRENT_DATE),
       ('Afghanistan', 'AF', CURRENT_DATE),
       ('Tajikistan', 'TJ', CURRENT_DATE),
       ('Kyrgyzstan', 'KG', CURRENT_DATE),
       ('Turkmenistan', 'TM', CURRENT_DATE),
       ('Iran', 'IR', CURRENT_DATE),
       ('Syria', 'SY', CURRENT_DATE),
       ('Armenia', 'AM', CURRENT_DATE),
       ('Sweden', 'SE', CURRENT_DATE),
       ('Belarus', 'BY', CURRENT_DATE),
       ('Ukraine', 'UA', CURRENT_DATE),
       ('Poland', 'PL', CURRENT_DATE),
       ('Austria', 'AT', CURRENT_DATE),
       ('Hungary', 'HU', CURRENT_DATE),
       ('Moldova', 'MD', CURRENT_DATE),
       ('Romania', 'RO', CURRENT_DATE),
       ('Lithuania', 'LT', CURRENT_DATE),
       ('Latvia', 'LV', CURRENT_DATE),
       ('Estonia', 'EE', CURRENT_DATE),
       ('Germany', 'DE', CURRENT_DATE),
       ('Bulgaria', 'BG', CURRENT_DATE),
       ('Greece', 'GR', CURRENT_DATE),
       ('Turkey', 'TR', CURRENT_DATE),
       ('Albania', 'AL', CURRENT_DATE),
       ('Croatia', 'HR', CURRENT_DATE),
       ('Switzerland', 'CH', CURRENT_DATE),
       ('Luxembourg', 'LU', CURRENT_DATE),
       ('Belgium', 'BE', CURRENT_DATE),
       ('Netherlands', 'NL', CURRENT_DATE),
       ('Portugal', 'PT', CURRENT_DATE),
       ('Spain', 'ES', CURRENT_DATE),
       ('Ireland', 'IE', CURRENT_DATE),
       ('New Caledonia', 'NC', CURRENT_DATE),
       ('Solomon Islands', 'SB', CURRENT_DATE),
       ('New Zealand', 'NZ', CURRENT_DATE),
       ('Australia', 'AU', CURRENT_DATE),
       ('Sri Lanka', 'LK', CURRENT_DATE),
       ('China', 'CN', CURRENT_DATE),
       ('Taiwan', 'TW', CURRENT_DATE),
       ('Italy', 'IT', CURRENT_DATE),
       ('Denmark', 'DK', CURRENT_DATE),
       ('United Kingdom', 'GB', CURRENT_DATE),
       ('Iceland', 'IS', CURRENT_DATE),
       ('Azerbaijan', 'AZ', CURRENT_DATE),
       ('Georgia', 'GE', CURRENT_DATE),
       ('Philippines', 'PH', CURRENT_DATE),
       ('Malaysia', 'MY', CURRENT_DATE),
       ('Brunei Darussalam', 'BN', CURRENT_DATE),
       ('Slovenia', 'SI', CURRENT_DATE),
       ('Finland', 'FI', CURRENT_DATE),
       ('Slovakia', 'SK', CURRENT_DATE),
       ('Czech Republic', 'CZ', CURRENT_DATE),
       ('Eritrea', 'ER', CURRENT_DATE),
       ('Japan', 'JP', CURRENT_DATE),
       ('Paraguay', 'PY', CURRENT_DATE),
       ('Yemen', 'YE', CURRENT_DATE),
       ('Saudi Arabia', 'SA', CURRENT_DATE),
       ('Northern Cyprus', 'CYP', CURRENT_DATE),
       ('Cyprus', 'CY', CURRENT_DATE),
       ('Morocco', 'MA', CURRENT_DATE),
       ('Egypt', 'EG', CURRENT_DATE),
       ('Libya', 'LY', CURRENT_DATE),
       ('Ethiopia', 'ET', CURRENT_DATE),
       ('Djibouti', 'DJ', CURRENT_DATE),
       ('Somaliland', 'SOM', CURRENT_DATE),
       ('Uganda', 'UG', CURRENT_DATE),
       ('Rwanda', 'RW', CURRENT_DATE),
       ('Bosnia and Herzegovina', 'BA', CURRENT_DATE),
       ('Macedonia', 'MK', CURRENT_DATE),
       ('Serbia', 'RS', CURRENT_DATE),
       ('Montenegro', 'ME', CURRENT_DATE),
       ('Kosovo', 'XK', CURRENT_DATE),
       ('Trinidad and Tobago', 'TT', CURRENT_DATE),
       ('South Sudan', 'SS', CURRENT_DATE);
